### ISSUE TITLE
Comatibility with next-gen update and F4SE v0.7.1, needs DLL rebuilt

### ISSUE THREAD

**Issue by mattmcadoo** [WirelessLan/DisableCompanionCollision#1]
Creating this as an issue stub for the latest version patching.

https://www.nexusmods.com/fallout4/mods/42147?tab=files

All native code plugins (.dlls) need to be updated by their creators for 1.10.980.
Old native code plugins not loading is not a problem with F4SE.

**Comment by WirelessLan** [comment]
Unfortunately, I currently have no plans to update this mod to accommodate the latest update. You will need to downgrade the game or modify the source code yourself to work with the latest update if necessary. (In fact, I have never downloaded the update myself and I will not)
